name: tosjoin # Replace with your actual project name.
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0 # Updated to match Dart 3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  table_calendar: ^3.1.2
  font_awesome_flutter: ^10.0.0
  get_storage: ^2.1.1
  path_provider: ^2.0.11
  flutter_dotenv: ^5.0.2
  http: ^1.1.0
  crypto: ^3.0.1
  google_fonts: ^6.2.1
  toastification: ^2.3.0
  loading_animation_widget: ^1.3.0
  typewritertext: ^3.0.9
  flutter_svg: ^2.0.16
  eva_icons_flutter: ^3.1.0
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  animate_do: ^3.3.4
  dismissible_page: ^1.0.2
  calendar_date_picker2: ^1.1.8
  intl: ^0.19.0
  khmer_date: ^1.0.3
  dotted_border: ^2.1.0
  file_picker: ^8.1.5
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_animarker: ^3.2.0
  month_picker_dialog: ^5.0.2
  url_launcher: ^6.3.1
  dio: ^5.7.0
  open_filex: ^4.6.0
  kalender: ^0.5.0
  timeline_tile: ^2.0.0
  fuzzy: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/technology.png
    - lib/assets/3d.png
    - lib/assets/ai.png
    - lib/assets/mobiledev.png
    - lib/assets/security.png
    - lib/assets/datascient.png
    - lib/assets/event1.jpg
