import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "sign-in": "SIGN IN",

          "not_arrived": "You are not arrived the location.",
          "welcome": "Welcome",
          "welcome_message": "Login to your account",
          "welcome_back": "Welcome back, ",
          "attendance": "Attendance",
          "attendance_d": "Check your attendance",
          "leave": "Leave",
          "leave_d": "History and request leave",
          "ot": "Overtime",
          "ot_d": "OT Request and History",
          "member": "Team Members",
          "member_d": "Check in/out members",
          "all-member": "Organization Members",
          "all-member-2": "Organization",
          "all-member_d": "Show all members in organization",
          "home": "Home",
          "payroll": "Payroll",
          "kpi": "KPI",
          "kpi_me": "Evaluation",
          "kpi_team": "Member Evaluation",
          "me": "ME",
          "profile": "Profile",
          "edit_profile": "Edit Profile",
          "privacy_policy": "Privacy Policy",
          "sign_out": "Sign out",
          "name": "Name",
          "password": "Password",
          "email": "Email",
          "position": "Position",
          "roll": "Roll",
          "contract": "Contract",
          "phone": "Phone",
          "address": "Address",
          "update": "Update",
          "theme": "Appearance",
          "dark": "Dark Mode",
          "light": "Light Mode",
          "system": "System",
          "non-staff": "non-staff",
          "request-demo": "Click to start demo",
          "deleted-account": "Delete Account",
          "text-confirm":
              "Deleting your account will permanently remove all public and private information associated with your profile.",
          "text-type": "To confirm this, type ",
          "search": "Search",
          "term": "Term and Condition",
          "manage": "Manage",

          "filter_year": "Choose Year",
          "filter_month": "Choose Month",
          "date": "Date",
          "interest_rate": "Interest rate",

          // Attendance
          "time": "Time",
          "action": "Action",
          "note": "Note",
          "type_here": "Type your note here",
          "history": "History",
          "submit": "Submit",

          // Leave
          "personal": "Personal @name",
          "team": "@name Requests",
          "kh": "ខ្មែរ",
          "en": "English",
          "language": "Language",
          "select_language": "Select Language",
          "hour": "Hour",

          //Status
          "approved": "Approved",
          "cancelled": "Cancel",
          "amount": "Amount",
          "rejected": "Rejected",
          "pending": "Pending",
          "day": "day",

          // Form
          "leave_detail": "Leave Detail",
          "ot_detail": "Overtime Detail",
          "leave_form": "Leave Form",
          "ot_form": "Overtime Form",
          "from_date": "From Date",
          "to_date": "To Date",
          "from_time": "From Time",
          "to_time": "To Time",

          "reason": "Reason",
          "status": "Status",
          "attachment": "Attachments",
          "requested_at": "Requested At",
          "delete": "Delete",
          "gallery": "Gallery",
          "camera": "Camera",
          "no_record": "No Records",
          "salary_in": "Salary in",

          // Status Attendance
          "InLate": "Arrived Late",
          "InOnTime": "Arrived On Time",
          "InEarly": "Arrived Early",
          "OutLate": "Left Late",
          "OutOnTime": "Left On Time",
          "OutEarly": "Left Early",

          "Notional": "Notional",
          "Regional": "Regional",
          "Public": "Public",
          "Local": "Local",

          "check_out": "Check Out",
          "check_in": "Check In",
          "CheckIn": "Check In",
          "CheckOut": "Check Out",

          "type_leave": "Type Leave",
          "type_d": "Manage type of leave for group",

          "member_d2": "Manage member such remove, schedule",
          "holiday": "Holiday",
          "holiday_d": "Manage holiday for organization",
          "location": "Locations",
          "location_d": "Manage location for organization",
          "company": "Company",
          "company_d": "Information for your group",

          "type": "Type",
          "limit": "Limit",
          "type-here": "type here",
          "add": "Add",
          "my-member": "My Member",
          "yes": "Yes",
          "no": "No",
          "sign-out-d": "Are you sure you want to sign out?",
          "name_required": "Name is required",
          "request-owner": "Request Owner",
          "all": "All",
          "duration": "Duration",
          "approved_by": "Approved By",
          "leave-stats": "Leave Stats",
          "upload": "Upload",
          "upload-d": "Upload your attachment here, \n max 5MB, limit 2 files",
          'number_of_days': 'enter number of days',
          "leader": "Leader",
          "error": "Something went wrong",
          "edit": "Edit",
          "check-by": "Check by",
          "company-info": "Company Information",
          "schedule-info": "Schedule Information",
          "schedule": "Schedule",
          "created_at": "Created At",
          "member-m": "Manage Member",
          "assign": "Assign",
          "assign-leader": "Assign Leader",
          "assign-member": "Assign Member",
          "apply-filter": "Apply Filter",
          "position-filter": "Choose Position",
          "contract-filter": "Choose Contract",
          "apply": "Apply",
          "January": "January",
          "February": "February",
          "March": "March",
          "April": "April",
          "May": "May",
          "June": "June",
          "July": "July",
          "August": "August",
          "September": "September",
          "October": "October",
          "November": "November",
          "December": "December",
          "map": "Map",
          "generate": "Generate",
          "turn_on": "Turn On",
          "turn_off": "Turn Off",
          "code": "Code",
          "lat-lng": "Latitude and Longitude",
          "range": "Range",
          "group-code": "Group Code",
          "group-d": "Please entering your group code to continues the process",
          "confirm": "Confirm",
        },
        "kh_CM": {
          "sign-in": "ចូលគណនី",
          "not_arrived": "អ្នកមិនទាន់ទៅដល់ទីតាំងការងារទេ។",
          "welcome": "សូមស្វាគមន៏",
          "welcome_message": "ចូលទៅគណនីរបស់អ្នក",
          "welcome_back": "ស្វាគមន៏ការត្រលប់មកវិញ, ",
          "attendance": "វត្តមាន",
          "attendance_d": "ពិនិត្យវត្តមានរបស់អ្នក",
          "leave": "សុំច្បាប់",
          "leave_d": "កត់ត្រា និងស្នើសុំច្បាប",
          "ot": "បន្ថែមម៉ោង",
          "ot_d": "កត់ត្រា និងស្នើសបន្ថែមម៉ោង",
          "member": "សមាជិកក្រុម",
          "member_d": "វត្តមានសមាជិកក្រុម",
          "all-member": "សមាជិកទាំងអស់",
          "all-member-2": "សមាជិកទាំងអស់",
          "all-member_d": "បង្ហាញសមាជិកទាំងអស់ក្នុងស្ថាប័ន",
          "home": "ទំព័រដើម",
          "payroll": "ប្រាក់បៀវត្សរ៍",
          "kpi": "KPI",
          "kpi_me": "ការវាយតម្លៃ",
          "kpi_team": "ការវាយតម្លៃសមាជិក",
          "me": "គណនី",
          "profile": "ប្រូហ្វាល់",
          "edit_profile": "កែសម្រួលប្រវត្តិរូប",
          "privacy_policy": "គោលការណ៍ភាពឯកជន",
          "sign_out": "ចាកចេញ",
          "name": "ឈ្មោះ",
          "password": "ពាក់សំងាត់",
          "email": "អ៊ីមែល",
          "position": "តួនាទី",
          "roll": "តួនាទី",
          "contract": "កិច្ចសន្យា",
          "phone": "ទូរស័ព្ទ",
          "address": "អាស័យដ្ឋាន",
          "update": "អាប់ដេត",
          "theme": "រូបរាង",
          "dark": "រចនាប័ទ្មងងឹត",
          "light": "រចនាប័ទ្មភ្លឺ",
          "system": "ដោយស្វ័យប្រវត្តិ",
          "text-confirm":
              "ការលុបគណនីរបស់អ្នកនឹងលុបជាអចិន្ត្រៃយ៍នូវព័ត៌មានសាធារណៈ និងឯកជនដែលពាក់ព័ន្ធជាមួយកម្រងព័ត៌មានរបស់អ្នក។",
          "text-type": "ដើម្បីបញ្ជាក់ សូមវាយបញ្ចូល ",
          "manage": "គ្រប់គ្រង",

          "filter_year": "ជ្រើសរើសឆ្នាំ",
          "filter_month": "ជ្រើសរើសខែ",
          "date": "កាលបរិច្ឆេទ",
          "interest_rate": "អត្រាការប្រាក់",

          // Attendance
          "time": "ពេលវេលា",
          "action": "សកម្មភាព",
          "note": "ចំណាំ",
          "type_here": "វាយកំណត់ចំណាំរបស់អ្នកនៅទីនេះ",
          "history": "កត់ត្រា",
          "submit": "ដាក់ស្នើ",
          "non-staff": "មិនមែនបុគ្គលិក",
          "request-demo": "ចុចដើម្បីចាប់ផ្តើមការបង្ហាញ",
          "deleted-account": "លុបគណនី",

          // Leave
          "personal": "@name ផ្ទាល់ខ្លួន",
          "team": "សំណើ @name",
          "kh": "ខ្មែរ",
          "en": "English",
          "language": "ភាសា",
          "select_language": "ជ្រើសរើសភាសា",

          //Status
          "approved": "អនុម័ត",
          "cancelled": "បោះបង់",
          "amount": "ចំនួន",
          "rejected": "ច្រានចោល",
          "pending": "កំពុងរង់ចាំ",
          "day": "ថ្ងៃ",
          "hour": "ម៉ោង",

          // Form
          "leave_detail": "ព័ត៌មានលំអិត",
          "ot_detail": "ព័ត៌មានលំអិត",
          "leave_form": "បំពេញទម្រង់",
          "ot_form": "បំពេញទម្រង់",
          "from_date": "ចាប់ពីថ្ងៃទី",
          "to_date": "ដល់ថ្ងៃទី",
          "from_time": "ចាប់ពីម៉ោង",
          "to_time": "ដល់ម៉ោង",
          "reason": "ហេតុផល",
          "status": "ស្ថានភាព",
          "attachment": "ឯកសារយោង",
          "requested_at": "បានស្នើសុំនៅថ្ងៃ",
          "delete": "លុប",
          "gallery": "អាល់ប៊ុម",
          "camera": "កាមេរ៉ា",
          "no_record": "មិនមានទិទ្នន័យ",
          "salary_in": "ប្រាក់បៀវត្សរ៍ប្រចាំខែ",
          "search": "ស្វែងរក",

          // Status Attendance
          "InLate": "មកយឺត",
          "InOnTime": "មកប្រសិន",
          "InEarly": "មកមុន",
          "OutLate": "ចេញយឺត",
          "OutOnTime": "ចេញប្រសិន",
          "OutEarly": "ចេញមុន",

          "Notional": "ជាតិ",
          "Regional": "តំបន់",
          "Public": "សាធារណៈ",
          "Local": "មូលដ្ឋាន",

          "check_out": "ចេញ",
          "check_in": "ចូល",
          "CheckIn": "ចូល",
          "CheckOut": "ចេញ",
          "term": "រយៈពេល និងលក្ខខណ្ឌ",

          "type_leave": "ប្រភេទច្បាប់",
          "type_d": "គ្រប់គ្រងប្រភេទនៃការសុំច្បាបសម្រាប់ក្រុម",
          "member_d2": "គ្រប់គ្រងសមាជិកដោយការលុប, កំណត់ពេលសមាជិក",
          "holiday": "ថ្ងៃឈប់",
          "holiday_d": "គ្រប់គ្រងថ្ងៃឈប់សមាជិក",
          "location": "ទីតាំង",
          "location_d": "គ្រប់គ្រងទីតាំងសមាជិក",
          "company": "ក្រុមហ៊ុន",
          "company_d": "គ្រប់គ្រងព័ត៏មានក្រុមហ៊ុន",
          "type": "ប្រភេទ",
          "limit": "កំណត់ចំនួន",
          "type-here": "វាយនៅទីនេះ",
          "add": "រក្សាទុក",
          "my-member": "ក្រុមរបស់ខ្ញំ",
          "yes": "បាទ/ចាស",
          "no": "ទេ",
          "sign-out-d": "តើអ្នកប្រាកចចេញពីគណនីរបស់អ្នកមែនទេ?",
          "name_required": "ឈ្មោះត្រូវបានបញ្ចូល",
          "request-owner": "ទម្រង់ស្នើសុំក្រុម",
          "all": "ទាំងអស់",
          "duration": "រយៈពេល",
          "approved_by": "អនុម័តដោយ",
          "leave-stats": "តារាងសុំច្បាប់",
          "upload": "អាប់ឡូត",
          "upload-d":
              "ផ្ទុកឯកសារយោងរបស់អ្នកនៅទីនេះ, \n អតិបរមាគឺ 5MB, កំណត់សំរាប់ឯកសារ 2 ឯកសារ",
          'number_of_days': 'បញ្ចូលចំនួនថ្ងៃ',
          "leader": "អ្នកដឹកនាំ",
          "error": "មានបញ្ហាមួយហើយ",
          "edit": "កែសម្រួល",
          "check-by": "ឆេកដោយ",
          "company-info": "ព័ត៏មានក្រុមហ៊ុន",
          "schedule": "កាលវិភាគ",
          "schedule-info": "ព័ត៏មានកាលវិភាគ",
          "created_at": "បានបង្កើតនៅថ្ងៃ",
          "member-m": "គ្រប់គ្រងសមាជិក",
          "assign": "កំណត់តួនាទី",
          "assign-leader": "កំណត់អ្នកដឹកនាំ",
          "assign-member": "កំណត់សមាជិក",
          "apply-filter": "ស្វែងរក",
          "position-filter": "ជ្រើសរើសតួនាទី",
          "contract-filter": "ជ្រើសរើសកិច្ចសន្យា",
          "apply": "អនុវត្ត",
          "January": "មករា",
          "February": "កុម្ភៈ",
          "March": "មីនា",
          "April": "មេសា",
          "May": "ឧសភា",
          "June": "មិថុនា",
          "July": "កក្កដា",
          "August": "សីហា",
          "September": "កញ្ញា",
          "October": "តុលា",
          "November": "វិច្ឆិកា",
          "December": "ធ្នូ",
          "map": "ផែនទី",
          "generate": "បង្កើតកូដ",
          "turn_on": "បើក",
          "turn_off": "បិទ",
          "code": "កូដ",
          "lat-lng": "អក្សរសម្ព័ន្ធ",
          "range": "ចម្ងាយ",
          "group-code": "កូដក្រុម",
          "group-d": "សូមវាយកូដក្រុមរបស់អ្នកដើម្បីបន្តបន្ទាប់ដោយដំណើរការ",
          "confirm": "បញ្ជាក់",
        }
      };
}
